# install: conda env create -f environment.yml
# update:  conda env update -f environment.yml

name: twop
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - jupyter
  # - nb_conda
  # - nb_conda_kernels
  - matplotlib
  - tqdm
  - pydantic
  - psygnal
  - pip:
    - scikit-learn
    - suite2p
    - oasis-deconv
    - pysimplegui
    - psygnal
    - pytomlpp
    - pyyaml
    - appdirs